name: pageon_flutter_example
description: Demo app for pageon_flutter
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  pageon_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf
